#!groovy

pipeline {

     agent any
    
    stages{
        
        stage('Paso 1') {
            steps{
                script{
                    println("proyecto 2")
                }
            }
        }
                
    }
}